name: Publish Android SDK

on:
  release:
    types: [published]

env:
  ANDROID_API_LEVEL: 33
  CI: true

jobs:
  test:
    uses: ./.github/workflows/test.yaml
  publish:
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_TOKEN_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_TOKEN_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Restore gradle.properties
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
      
      - name: Publish and Release to Maven Central Portal
        working-directory: eppo
        run: ../gradlew publishAndReleaseToMavenCentral -Prelease --no-daemon --no-configuration-cache

      - name: Upload build artifacts and logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-and-artifacts-${{ github.run_number }}
          path: |
            build/**
            eppo/**
            **/build/libs/**
            **/hs_err_pid*.log
          retention-days: 7
