name: Test and lint SDK
on:
  pull_request:
    paths:
      - '**/*'

env:
  ANDROID_API_LEVEL: 33

jobs:
  lint-test-sdk:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 34
          profile: Pixel 3a
          target: google_apis
          arch: x86_64
          disable-animations: true
          script: make test-github-wf
        env:
          MAVEN_USERNAME: test
          MAVEN_PASSWORD: test
