name: Test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**/*'

jobs:
  test-android-sdk:
    runs-on: macos-latest
    steps:
      - name: Check out Java SDK
        uses: actions/checkout@v3
        with:
          repository: 'Eppo-exp/android-sdk'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: 'Set up GCP SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Restore gradle.properties
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "MAVEN_USERNAME=${MAVEN_USERNAME}" > ~/.gradle/gradle.properties
          echo "MAVEN_PASSWORD=${MAVEN_PASSWORD}" >> ~/.gradle/gradle.properties

      - name: Set up test data
        run: make test-data

      - name: Wait for mock RAC DNS to resolve
        run: |
          for i in {1..15}
          do
            ip=$(dig +short us-central1-eppo-prod-312905.cloudfunctions.net)
            if [[ -n "$ip" ]]; then
              echo "Domain resolved to $ip after $i seconds"
              exit 0
            fi
            sleep 1
          done
          echo "Failed to resolve after 15 seconds"
          exit 1

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-33

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Spin up emulator and run tests
        id: testing
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -netdelay none -netspeed full -dns-server 8.8.8.8
          disable-animations: true
          script: |
            echo "Emulator started" 
            adb logcat -c                                     # clear logs
            mkdir -p app/                                     # create directory
            touch app/emulator.log                            # create log file
            chmod 777 app/emulator.log                        # allow writing to log file
            adb logcat | grep EppoSDK >> app/emulator.log &   # pipe all logcat messages into log file as a background process
            ./gradlew connectedCheck                          # run tests

      - name: Upload Emulator Logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: emulator logs
          path: app/emulator.log

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: /Users/runner/work/android-sdk/android-sdk/eppo/build/reports/androidTests/connected/index.html