name: Test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**/*'

jobs:
  test-android-sdk:
    runs-on: macos-latest
    env:
      ANDROID_API_LEVEL: 33
    steps:
      - name: Check out Java SDK
        uses: actions/checkout@v3
        with:
          repository: 'Eppo-exp/android-sdk'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: 'Set up GCP SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Restore gradle.properties
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "MAVEN_USERNAME=${MAVEN_USERNAME}" > ~/.gradle/gradle.properties
          echo "MAVEN_PASSWORD=${MAVEN_PASSWORD}" >> ~/.gradle/gradle.properties
      - name: Set up test data
        run: make test-data
      - name: Spin up emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          script: |
            echo "Emulator started" 
            ./gradlew connectedCheck